phpcs:
  files: src/
  standards: [PSR1, PSR2]
phpmd:
  files: src/
function_blacklist:
  files: src/
  blacklist:
    die: notice
    echo: notice
    var_dump: error
comment_blacklist:
  files: src/
  blacklist:
    todo: notice
    "dont commit": error
security-checker:
  directory: ./
  level: critical
twig_lint:
  files: src/
