#!/bin/bash

VAR_DIR=var
CONSOLE_DIR=bin

mkdir -p /etc/${DPKG_MAINTSCRIPT_PACKAGE}/

ln -sf /etc/${DPKG_MAINTSCRIPT_PACKAGE}/parameters.yml /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/app/config/parameters.yml
rm -Rf /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${VAR_DIR}/logs

mkdir -p /var/log/${DPKG_MAINTSCRIPT_PACKAGE}
chown -R www-data /var/log/${DPKG_MAINTSCRIPT_PACKAGE}
ln -s /var/log/${DPKG_MAINTSCRIPT_PACKAGE} /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${VAR_DIR}/logs

mkdir -p /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${VAR_DIR}/cache/

chown -R root:www-data /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/
chown -R www-data /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${VAR_DIR}/cache/

chmod -R g-w,g+rX,o-rwx /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/
chmod a+x /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${CONSOLE_DIR}/console

sudo -u www-data /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${CONSOLE_DIR}/console --env=prod cache:clear
sudo -u www-data /usr/share/st-applications/${DPKG_MAINTSCRIPT_PACKAGE}/${CONSOLE_DIR}/console doctrine:migrations:migrate --no-interaction